---
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest on notebooks
        language: system
        always_run: true
        pass_filenames: false
        stages: [commit]
        verbose: true
        entry: bash -c "pytest || echo 'note tests failed, continuing commit'"
