---
version: "3.9"
networks:
  mit-api:
    driver: bridge
    name: mit-api
services:
  api:
    container_name: mit-annotation-api
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - GIT_COMMIT_SHA=${COMMIT_SHA:-unknown}
      - APP_VERSION=${VERSION:-unknown}
    ports:
      - "8000:8000"
    networks:
      - mit-api
